In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

index = pd.read_csv("Index",sep = " ",skiprows=1, header = None)
index
names = ["Alcohol", "Malic acid", "Ash", "Alcalinity of ash", "Magnesiu", "Total phenols", "Flavanoids", "Nonflavanoid phenols", "Proanthocyanins", "Color intensity", "Hue", "OD280/OD315 of diluted wines", "Proline"]
wine = pd.read_csv("wine.data", header=None , names=names)

wine

Alcohol  Malic acid   Ash  Alcalinity of ash  Magnesiu  Total phenols  \
1     14.23        1.71  2.43               15.6       127           2.80   
1     13.20        1.78  2.14               11.2       100           2.65   
1     13.16        2.36  2.67               18.6       101           2.80   
1     14.37        1.95  2.50               16.8       113           3.85   
1     13.24        2.59  2.87               21.0       118           2.80   
..      ...         ...   ...                ...       ...            ...   
3     13.71        5.65  2.45               20.5        95           1.68   
3     13.40        3.91  2.48               23.0       102           1.80   
3     13.27        4.28  2.26               20.0       120           1.59   
3     13.17        2.59  2.37               20.0       120           1.65   
3     14.13        4.10  2.74               24.5        96           2.05   

    Flavanoids  Nonflavanoid phenols  Proanthocyanins  Color intensity   Hue  \
1         3.06                  0.28             2.29             5.64  1.04   
1         2.76                  0.26             1.28             4.38  1.05   
1         3.24                  0.30             2.81             5.68  1.03   
1         3.49                  0.24             2.18             7.80  0.86   
1         2.69                  0.39             1.82             4.32  1.04   
..         ...                   ...              ...              ...   ...   
3         0.61                  0.52             1.06             7.70  0.64   
3         0.75                  0.43             1.41             7.30  0.70   
3         0.69                  0.43             1.35            10.20  0.59   
3         0.68                  0.53             1.46             9.30  0.60   
3         0.76                  0.56             1.35             9.20  0.61   

    OD280/OD315 of diluted wines  Proline  
1                           3.92     1065  
1                           3.40     1050  
1                           3.17     1185  
1                           3.45     1480  
1                           2.93      735  
..                           ...      ...  
3                           1.74      740  
3                           1.56      750  
3                           1.56      835  
3                           1.62      840  
3                           1.60      560  

[178 rows x 13 columns]

In [ ]:
y = wine.index
x = wine
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

df = MinMaxScaler()

X_train_nor = df.fit_transform(X_train)

X_test_nor= df.transform(X_test)

Normalizacji używamy w celu sprowadzenia wszystkich zmiennych do podobnego zakresu, aby były łatwiejsze do porównania, co pozwala na otrzymanie lepszych wyników.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

kn = KNeighborsClassifier()
kn.fit(X_train_nor, y_train)
kn = kn.predict(X_test_nor)

rf = RandomForestClassifier()
rf.fit(X_train_nor, y_train)
rf = rf.predict(X_test_nor)

Accuracy -  liczy stosunek dobrych predykcji do wszystkich, pokazuje dokładność predykcji

In [ ]:
from sklearn.metrics import accuracy_score

kn_ac = accuracy_score(y_test, kn)
print("Dokładność KNeighborsClassifier:", kn_ac)
rf_ac = accuracy_score(y_test, rf)
print("Dokładność RandomForestClassifier:", rf_ac)

Dokładność KNeighborsClassifier: 0.9444444444444444
Dokładność RandomForestClassifier: 1.0


Precision - liczy stosunek poprawnie zidentyfikowanych pozytywnych przypadków wśród wszystkich przypadków zidentyfikowanych jako pozytywne, pokazuje wpływ fałszych pozytywnych wyników


In [ ]:
from sklearn.metrics import precision_score

kn_precision = precision_score(y_test, kn, average='weighted')
print("Precyzja dla KNeighborsClassifier:", kn_precision)

rf_precision = precision_score(y_test, rf, average='weighted')
print("Precyzja dla RandomForestClassifier:", rf_precision)

Dokładność KNeighborsClassifier: 0.23570226039551584
Dokładność KNeighborsClassifier: 0.0


Recall - liczba dobrych predykcji do wszystkich, używamy do minimalizacji pomijania przypadków

In [ ]:
from sklearn.metrics import recall_score

kn_recall = recall_score(y_test, kn, average='weighted')
print("Recall dla KNeighborsClassifier:", kn_recall)

rf_recall = recall_score(y_test, rf, average='weighted')
print("Recall dla RandomForestClassifier:", rf_recall)


Recall dla KNeighborsClassifier: 0.9444444444444444
Recall dla RandomForestClassifier: 1.0


 F-measures - średnia harmoniczna precision i recall, uwzględnia zatem precyzję i czułość modelu



In [ ]:
from sklearn.metrics import f1_score

kn_f1 = f1_score(y_test, kn, average='weighted')
print("F-measure dla KNeighborsClassifier:", kn_f1)

rf_f1 = f1_score(y_test, rf, average='weighted')
print("F-measure dla RandomForestClassifier:", rf_f1)


F-measure dla KNeighborsClassifier: 0.9436036129748098
F-measure dla RandomForestClassifier: 1.0


Confusion matrix - macierz pomyłek, na głownej osi ma ilość trafionych predykcji, reszta to ilości nietrafionych.


In [ ]:
from sklearn.metrics import confusion_matrix

kn_conf_matrix = confusion_matrix(y_test, kn)
print("Macierz pomyłek dla KNeighborsClassifier:")
print(kn_conf_matrix)

rf_conf_matrix = confusion_matrix(y_test, rf)
print("Macierz pomyłek dla RandomForestClassifier:")
print(rf_conf_matrix)

Macierz pomyłek dla KNeighborsClassifier:
[[14  0  0]
 [ 1 12  1]
 [ 0  0  8]]
Macierz pomyłek dla RandomForestClassifier:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]


classification raport - to podsumowanie kluczowych metryk oceny klasyfikacji dla każdej z klas, zawiera precyzję, czułość, F-measure i liczbę obserwacji dla każdej klasy.

In [ ]:
from sklearn.metrics import classification_report

kn_classification_report = classification_report(y_test, kn)
print("Raport klasyfikacji dla KNeighborsClassifier:")
print(kn_classification_report)

# Raport klasyfikacji dla RandomForestClassifier
rf_classification_report = classification_report(y_test, rf)
print("Raport klasyfikacji dla RandomForestClassifier:")
print(rf_classification_report)


Raport klasyfikacji dla KNeighborsClassifier:
              precision    recall  f1-score   support

           1       0.93      1.00      0.97        14
           2       1.00      0.86      0.92        14
           3       0.89      1.00      0.94         8

    accuracy                           0.94        36
   macro avg       0.94      0.95      0.94        36
weighted avg       0.95      0.94      0.94        36

Raport klasyfikacji dla RandomForestClassifier:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00        14
           2       1.00      1.00      1.00        14
           3       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



Analiza predykcji:

oba modele dobrze dopasowują się do danych, ale model lasu regresyjnego robi to idealnie, dobrze sklasyfikował wszystkie rekordy zbioru testowego.
Jest prawdopodobieństwo przetrenowania algorytmu k-sąsiadów,ze względu na niewielką ilość danych, algortm lasu regresyjnego jest odporniejszy na takie przypadki, dzięki drzewom decyzyjnym.